VI for near edge storm and 20x20deg

diff --git a/jobs/JHAFS_ATM_IC b/jobs/JHAFS_ATM_IC
--- a/jobs/JHAFS_ATM_IC
+++ b/jobs/JHAFS_ATM_IC
@@ -69,20 +69,65 @@ fi
 
 export FGAT_HR=${FGAT_HR:-00}
 
-if [ "${SCRUBDATA:-YES}" = "YES" ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
 
-# Execute ex-script
-${HOMEhafs}/scripts/exhafs_atm_ic.sh
-export err=$?; err_chk
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
+run_needed=NO
+if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
+  echo 'outside parent domain'
+  run_needed=YES
+  export run_needed=YES
 fi
 
+if [ "${run_needed}" = "YES" ]; then
+  if [ ${ENSDA} = YES ]; then
+    export DATA=${WORKhafs}/atm_ic_ens/mem${ENSID}${jobidstr}
+  elif [ ${FGAT_MODEL} = gdas ]; then
+    export DATA=${WORKhafs}/atm_ic_fgat${FGAT_HR}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_ic${jobidstr}
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_ic.sh
+  export err=$?; err_chk
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_ic_test.sh
+  export err=$?; err_chk
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+else
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_ic.sh
+  export err=$?; err_chk
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+fi
 date
diff --git a/jobs/JHAFS_ATM_INIT b/jobs/JHAFS_ATM_INIT
--- a/jobs/JHAFS_ATM_INIT
+++ b/jobs/JHAFS_ATM_INIT
@@ -66,32 +66,102 @@ if [ ${FGAT_MODEL} = gdas ]; then
   export out_prefix="${STORMID,,}.${CDATE}"
 fi
 
-if [ "${ENSDA}" = YES ] && [ "${ENSID}" != "000" ]; then
-  export DATA=${WORKhafs}/atm_init_ens/mem${ENSID}${jobidstr}
-  export nest_grids=${nest_grids_ens:-1}
-elif [ ${FGAT_MODEL} = gdas ]; then
-  export DATA=${WORKhafs}/atm_init_fgat${FGAT_HR}${jobidstr}
+################################################
+export FGAT_MODEL=${FGAT_MODEL:-gfs}
+export FGAT_HR=${FGAT_HR:-00}
+
+run_needed=NO
+if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
+  echo 'outside parent domain'
+  run_needed=YES
+  export run_needed=YES
+fi
+
+if [ "${run_needed}" = "YES" ]; then
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/atm_init_ens/mem${ENSID}${jobidstr}
+    elif [ ${FGAT_MODEL} = gdas ]; then
+      export DATA=${WORKhafs}/atm_init_fgat${FGAT_HR}${jobidstr}
+    else
+      export DATA=${WORKhafs}/atm_init${jobidstr}
+    fi
+
+    if [ "${SCRUBDATA:-YES}" = YES ]; then
+      rm -rf $DATA
+    fi
+    mkdir -p $DATA
+    cd $DATA
+
+    # Add multistorm env vars
+    export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
+
+    # Execute ex-script
+    ${HOMEhafs}/scripts/exhafs_atm_init.sh
+    export err=$?; err_chk
+
+    # Cleanup DATA dir
+    cd ${WORKhafs}
+    if [ "${KEEPDATA:-YES}" != "YES" ]; then
+
+      rm -rf $DATA
+    fi
+
+##    
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/atm_merge_init_ens/mem${ENSID}${jobidstr}
+    elif [ ${FGAT_MODEL} = gdas ]; then
+      export DATA=${WORKhafs}/atm_merge_init_fgat${FGAT_HR}${jobidstr}
+    else
+      export DATA=${WORKhafs}/atm_merge_init${jobidstr}
+    fi
+
+    if [ "${SCRUBDATA:-YES}" = YES ]; then
+      rm -rf $DATA
+    fi
+    mkdir -p $DATA
+    cd $DATA
+
+    # Add multistorm env vars
+    export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
+
+    # Execute ex-script
+    ${HOMEhafs}/scripts/exhafs_atm_init_test.sh
+    export err=$?; err_chk
+    # Cleanup DATA dir
+    cd ${WORKhafs}
+    if [ "${KEEPDATA:-YES}" != "YES" ]; then
+      rm -rf $DATA
+    fi
 else
-  export DATA=${WORKhafs}/atm_init${jobidstr}
+####
+
+  if [ "${ENSDA}" = YES ] && [ "${ENSID}" != "000" ]; then
+    export DATA=${WORKhafs}/atm_init_ens/mem${ENSID}${jobidstr}
+    export nest_grids=${nest_grids_ens:-1}
+  elif [ ${FGAT_MODEL} = gdas ]; then
+    export DATA=${WORKhafs}/atm_init_fgat${FGAT_HR}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_init${jobidstr}
+  fi
+  
+  if [ "${SCRUBDATA:-YES}" = YES ] && [ "${ENSDA}" != YES ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Add multistorm env vars
+  export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
+  
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_init.sh
+  export err=$?; err_chk
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 fi
-
-if [ "${SCRUBDATA:-YES}" = YES ] && [ "${ENSDA}" != YES ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
-
-# Add multistorm env vars
-export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
-
-# Execute ex-script
-${HOMEhafs}/scripts/exhafs_atm_init.sh
-export err=$?; err_chk
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
-fi
-
 date
diff --git a/jobs/JHAFS_ATM_LBC b/jobs/JHAFS_ATM_LBC
--- a/jobs/JHAFS_ATM_LBC
+++ b/jobs/JHAFS_ATM_LBC
@@ -60,27 +60,89 @@ export BC_CLEANUP=${BC_CLEANUP:-NO}
 export BC_GROUPN=${BC_GROUPN:-1}
 export BC_GROUPI=$( printf "%d" "${BC_GROUPI:-1}" )
 
-# Deterministic or ensemble
-if [ ${ENSDA} != YES ]; then
-  export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}${jobidstr}
+################################################
+export FGAT_MODEL=${FGAT_MODEL:-gfs}
+export FGAT_HR=${FGAT_HR:-00}
+
+run_needed=NO
+if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
+  echo 'outside parent domain'
+  run_needed=YES
+  export run_needed=YES
+fi
+
+#########################################
+if [ "${run_needed}" = "YES" ]; then
+
+  # Deterministic or ensemble
+  if [ ${ENSDA} != YES ]; then
+    export DATA=${WORKhafs}/atm_merge_lbc${BC_GROUPI}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_merge_lbc${BC_GROUPI}_ens/mem${ENSID}${jobidstr}
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_lbc_test.sh
+  export err=$?; err_chk
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
+  # Deterministic or ensemble
+  if [ ${ENSDA} != YES ]; then
+    export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}_ens/mem${ENSID}${jobidstr}
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_lbc.sh
+  export err=$?; err_chk
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 else
-  export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}_ens/mem${ENSID}${jobidstr}
+  ###
+  # Deterministic or ensemble
+  if [ ${ENSDA} != YES ]; then
+    export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_lbc${BC_GROUPI}_ens/mem${ENSID}${jobidstr}
+  fi
+  
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_lbc.sh
+  export err=$?; err_chk
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
 fi
-
-if [ "${SCRUBDATA:-YES}" = "YES" ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
-
-# Execute ex-script
-${HOMEhafs}/scripts/exhafs_atm_lbc.sh
-export err=$?; err_chk
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
-fi
-
 date
diff --git a/jobs/JHAFS_ATM_PREP b/jobs/JHAFS_ATM_PREP
--- a/jobs/JHAFS_ATM_PREP
+++ b/jobs/JHAFS_ATM_PREP
@@ -57,42 +57,236 @@ source ${HOLDVARS}
 export ENSDA=${ENSDA:-NO}
 export ATM_PREP_MVNEST=${ATM_PREP_MVNEST:-NO}
 
-if [[ ${ATM_PREP_MVNEST:-NO} != YES ]]; then
+run_needed=NO
 
-# Deterministic or ensemble
-if [ ${ENSDA:-NO} = YES ]; then
-  export DATA=${WORKhafs}/atm_prep_ens${jobidstr}
+for FGAT_HR in 3 6 9; do
+  if [ ${FGAT_HR} -eq 3 ]; then
+      tcvital=${WORKhafs}/intercom/launch/tm03vit
+   elif [ ${FGAT_HR} -eq 9  ]; then
+      tcvital=${WORKhafs}/intercom/launch/tp03vit
+   else
+      tcvital=${WORKhafs}/intercom/launch/tmpvit
+  fi
+
+  lon_vit=$(cat ${tcvital} | cut -c39-42 | bc -l )
+  lon_vit=`echo "scale=1; $lon_vit/10" |bc `
+
+  lon_vit_hem=$(cat ${tcvital} | cut -c43)
+
+  lat_vit=$(cat ${tcvital} | cut -c34-36 | bc -l )
+  lat_vit=`echo "scale=1; $lat_vit/10" |bc `
+
+  lat_vit_hem=$(cat ${tcvital} | cut -c37)
+
+  echo $lon_vit $lon_vit_hem $lat_vit $lat_vit_hem
+
+  if [ $lon_vit_hem == 'W' ]; then
+  lon_vit=`echo "scale=1; ( $lon_vit - 360 ) *-1 " |bc `
+  fi
+
+  if [ $lat_vit_hem == 'S' ]; then
+  lat_vit=`echo "scale=1; $lat_vit * -1 " |bc `
+  fi
+
+  echo $lon_vit $lon_vit_hem $lat_vit $lat_vit_hem
+
+  vi_domain=${vi_domain:-40}
+  vi_domain_halfs=`echo "scale=1; $vi_domain / 2" |bc `
+
+  echo $vi_domain_halfs 
+
+  maxlon=`echo "scale=1; $lon_vit + $vi_domain_halfs " |bc `
+  minlon=`echo "scale=1; $lon_vit - $vi_domain_halfs " |bc `
+  maxlat=`echo "scale=1; $lat_vit + $vi_domain_halfs " |bc `
+  minlat=`echo "scale=1; $lat_vit - $vi_domain_halfs " |bc `
+
+  echo $minlon $maxlon $minlat $maxlat
+
+#  ldmlonmin=`head -n 1 $FIXhafs/fix_fv3/lon2087`
+#  ldmlonmax=`tail -n 1 $FIXhafs/fix_fv3/lon2087`
+#  
+#  rdmlonmin=`head -n 1 $FIXhafs/fix_fv3/lon0`
+#  rdmlonmin=`echo "scale=1; $rdmlonmin + 360" |bc `
+#  
+#  bdmlatmin=`head -n 1 $FIXhafs/fix_fv3/lat1049`
+#  bdmlatmax=`tail -n 1 $FIXhafs/fix_fv3/lat1049`
+#  
+#  udmlatmin=`head -n 1 $FIXhafs/fix_fv3/lat0`
+#  udmlatmax=`tail -n 1 $FIXhafs/fix_fv3/lat0`
+#  
+#  echo ' $rdmlonmin $rdmlonmax $ldmlonmin $ldmlonmax' $rdmlonmin $rdmlonmax $ldmlonmin $ldmlonmax $maxlon $minlon
+#  echo ' $udmlatmin $udmlatmax $bdmlatmin $bdmlatmax' $udmlatmin $udmlatmax $bdmlatmin $bdmlatmax $maxlat $minlat
+  #Could change the domain criteria
+
+  echo 'pubbasin2:' $pubbasin2
+
+#  if [ "$(echo "$CENLO < -100" | bc)" -eq 1 ]; then
+  if [ $pubbasin2 == 'AL' ] && [ $STORMID == '00L' ] ; then
+     if [ "$(echo "$CENLO < -100" | bc)" -eq 1 ]; then
+         echo 'pacific'
+         rdmlonmax=288  #Lon at right edge of parent domain
+         ldmlonmin=171  #Lon at left edge of parent domain
+         udmlatmax=52   #Lat at up edge of parent domain
+         bdmlatmin=0    #Lat at bottom edge of parent domain
+      else
+         echo 'atlantic'
+         rdmlonmax=358  #Lon at right edge of parent domain
+         ldmlonmin=259  #Lon at left edge of parent domain
+         udmlatmax=52   #Lat at up edge of parent domain
+         bdmlatmin=0    #Lat at bottom edge of parent domain
+      fi
+  elif [ $pubbasin2 == 'EP' ]; then
+     echo 'pacific'
+     rdmlonmax=288  #Lon at right edge of parent domain
+     ldmlonmin=171  #Lon at left edge of parent domain
+     udmlatmax=52   #Lat at up edge of parent domain
+     bdmlatmin=0    #Lat at bottom edge of parent domain
+  else
+     echo 'atlantic'
+     rdmlonmax=358  #Lon at right edge of parent domain
+     ldmlonmin=259  #Lon at left edge of parent domain
+     udmlatmax=52   #Lat at up edge of parent domain
+     bdmlatmin=0    #Lat at bottom edge of parent domain
+#  elif [ $pubbasin2 -eq 'AL' ] && [ $STORMID -ne '00L'] ; then
+#     echo 'atlantic'
+#     rdmlonmax=358  #Lon at right edge of parent domain
+#     ldmlonmin=245  #Lon at left edge of parent domain
+#     udmlatmax=52   #Lat at up edge of parent domain
+#     bdmlatmin=0    #Lat at bottom edge of parent domain
+  fi
+
+  echo '$rdmlonmin $rdmlonmax $udmlatmax $bdmlatmin ' $rdmlonmin $rdmlonmax $udmlatmax $bdmlatmin
+  echo '$lonmin $lonmax $latmax $latmin ' $lonmin $lonmax $latmax $latmin
+  is_outside=$(awk -v r="${rdmlonmax:-0}" -v rmax="${maxlon:-0}" \
+                   -v l="${ldmlonmin:-0}" -v lmin="${minlon:-0}" \
+                   -v u="${udmlatmax:-0}" -v umax="${maxlat:-0}" \
+                   -v b="${bdmlatmin:-0}" -v bmin="${minlat:-0}" '
+    BEGIN {
+      # Outside if
+      if (r < rmax || l > lmin || u < umax || b > bmin) print 1;
+      else print 0;
+    }')
+
+  vmax_vit=$(cat ${tcvital} | cut -c68-69 | bc -l)
+
+  if [[ "$is_outside" -eq 1 ]] &&  [[ ${vmax_vit} -gt ${vi_min_wind_for_init} ]] ; then
+    echo 'outside parent domain and ' ${vmax_vit} ' gt ' ${vi_min_wind_for_init}
+    run_needed=YES
+    export run_needed=YES
+  fi
+
+done
+
+if [ "${run_needed}" = "YES" ]; then
+  if [[ ${ATM_PREP_MVNEST:-NO} != YES ]]; then
+     export DATA=${WORKhafs}/atm_merge_prep${jobidstr}
+  else
+
+      if [[ "${is_moving_nest}" = *".true."* ]]; then
+      export DATA=${WORKhafs}/atm_merge_prep_mvnest${jobidstr}
+      fi
+
+   fi
+      if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+     rm -rf $DATA
+   fi
+   mkdir -p $DATA
+   cd $DATA
+
+   # Execute ex-script
+   if [[ "${run_datm:-no}" = "yes" ]]; then
+     ${HOMEhafs}/scripts/exhafs_datm_prep.sh
+     export err=$?; err_chk
+   else
+     ${HOMEhafs}/scripts/exhafs_atm_prep_test.sh
+     export err=$?; err_chk
+   fi
+
+   # Cleanup DATA dir
+   cd ${WORKhafs}
+   if [ "${KEEPDATA:-YES}" != "YES" ]; then
+     rm -rf $DATA
+   fi
+
+  if [[ ${ATM_PREP_MVNEST:-NO} != YES ]]; then
+
+##############    
+  # Deterministic or ensemble
+  if [ ${ENSDA:-NO} = YES ]; then
+
+    export DATA=${WORKhafs}/atm_prep_ens${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_prep${jobidstr}
+  fi
+
+  else # Moving nest is enabled
+
+  if [[ "${is_moving_nest}" = *".true."* ]]; then
+    export DATA=${WORKhafs}/atm_prep_mvnest${jobidstr}
+  fi
+
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  if [[ "${run_datm:-no}" = "yes" ]]; then
+    ${HOMEhafs}/scripts/exhafs_datm_prep.sh
+    export err=$?; err_chk
+  else
+    ${HOMEhafs}/scripts/exhafs_atm_prep.sh
+    export err=$?; err_chk
+  fi
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 else
-  export DATA=${WORKhafs}/atm_prep${jobidstr}
+
+  if [[ ${ATM_PREP_MVNEST:-NO} != YES ]]; then
+
+  # Deterministic or ensemble
+  if [ ${ENSDA:-NO} = YES ]; then
+    export DATA=${WORKhafs}/atm_prep_ens${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_prep${jobidstr}
+  fi
+  
+  else # Moving nest is enabled
+  
+  if [[ "${is_moving_nest}" = *".true."* ]]; then
+    export DATA=${WORKhafs}/atm_prep_mvnest${jobidstr}
+  fi
+  
+  fi
+  
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Execute ex-script
+  if [[ "${run_datm:-no}" = "yes" ]]; then
+    ${HOMEhafs}/scripts/exhafs_datm_prep.sh
+    export err=$?; err_chk
+  else
+    ${HOMEhafs}/scripts/exhafs_atm_prep.sh
+    export err=$?; err_chk
+  fi
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 fi
-
-else # Moving nest is enabled
-
-if [[ "${is_moving_nest}" = *".true."* ]]; then
-  export DATA=${WORKhafs}/atm_prep_mvnest${jobidstr}
-fi
-
-fi
-
-if [ "${SCRUBDATA:-YES}" = "YES" ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
-
-# Execute ex-script
-if [[ "${run_datm:-no}" = "yes" ]]; then
-  ${HOMEhafs}/scripts/exhafs_datm_prep.sh
-  export err=$?; err_chk
-else
-  ${HOMEhafs}/scripts/exhafs_atm_prep.sh
-  export err=$?; err_chk
-fi
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
-fi
-
 date
diff --git a/jobs/JHAFS_ATM_VI b/jobs/JHAFS_ATM_VI
--- a/jobs/JHAFS_ATM_VI
+++ b/jobs/JHAFS_ATM_VI
@@ -60,29 +60,103 @@ export ENSID=${ENSID:-000}
 export FGAT_MODEL=${FGAT_MODEL:-gfs}
 export FGAT_HR=${FGAT_HR:-00}
 
-# Deterministic or ensemble
-if [ "${ENSDA}" = YES ]; then
-  export DATA=${WORKhafs}/atm_vi_ens/mem${ENSID}${jobidstr}
-elif [ ${FGAT_MODEL} = gdas ]; then
-  export DATA=${WORKhafs}/atm_vi_fgat${FGAT_HR}${jobidstr}
+run_needed=NO
+if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
+  echo 'outside parent domain'
+  run_needed=YES
+  export run_needed=YES
+fi
+#########################################
+export RESTARTprev=${COMOLD}/${old_out_prefix}.RESTART
+
+if [ "${run_needed}" = "YES" ]; then #&& [ -d ${RESTARTprev}  ]; then
+#if [ "${run_needed}" = "YES" ]; then #&& [  = "YES" ]; then to-do later
+
+  echo "previous cycle exisit, merge first"
+  #merge first
+  export MERGE_TYPE=init
+  # Merge analysis or init
+  if [ ${MERGE_TYPE} = analysis ]; then
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
+    else
+      export DATA=${WORKhafs}/analysis_merge${jobidstr}
+    fi
+  elif [ ${MERGE_TYPE} = init ]; then
+    if [ ${FGAT_MODEL} = gdas ]; then
+      export DATA=${WORKhafs}/atm_merge_fgat${FGAT_HR}${jobidstr}
+    else
+      export DATA=${WORKhafs}/atm_merge${jobidstr}
+    fi
+  else
+    echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
+    exit 1
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+if [ -d ${RESTARTprev}  ]; then
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_merge_test.sh
+  export err=$?; err_chk
+fi
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
+  # Deterministic or ensemble
+  if [ "${ENSDA}" = YES ]; then
+    export DATA=${WORKhafs}/atm_vi_ens/mem${ENSID}${jobidstr}
+  elif [ ${FGAT_MODEL} = gdas ]; then
+    export DATA=${WORKhafs}/atm_vi_fgat${FGAT_HR}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_vi${jobidstr}
+  fi
+
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_vi_test.sh
+  export err=$?; err_chk
+
 else
-  export DATA=${WORKhafs}/atm_vi${jobidstr}
+
+  ####
+  # Deterministic or ensemble
+  if [ "${ENSDA}" = YES ]; then
+    export DATA=${WORKhafs}/atm_vi_ens/mem${ENSID}${jobidstr}
+  elif [ ${FGAT_MODEL} = gdas ]; then
+    export DATA=${WORKhafs}/atm_vi_fgat${FGAT_HR}${jobidstr}
+  else
+    export DATA=${WORKhafs}/atm_vi${jobidstr}
+  fi
+  
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_atm_vi.sh
+  export err=$?; err_chk
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 fi
-
-if [ "${SCRUBDATA:-YES}" = "YES" ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
-
-# Execute ex-script
-${HOMEhafs}/scripts/exhafs_atm_vi.sh
-export err=$?; err_chk
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
-fi
-
 date
diff --git a/jobs/JHAFS_MERGE b/jobs/JHAFS_MERGE
--- a/jobs/JHAFS_MERGE
+++ b/jobs/JHAFS_MERGE
@@ -64,50 +64,99 @@ export FGAT_HR=${FGAT_HR:-00}
 export RUN_MULTISTORM=${RUN_MULTISTORM:-NO}
 export FAKEWORKhafs=${FAKEWORKhafs:-$(echo "${WORKhafs/${STORMID}/${FAKESTORMID}}")}
 
-# Merge analysis or init
-if [ ${MERGE_TYPE} = analysis ]; then
-  if [ "${ENSDA}" = YES ]; then
-    export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
-  else
-    export DATA=${WORKhafs}/analysis_merge${jobidstr}
-  fi
-elif [ ${MERGE_TYPE} = init ]; then
-  if [ "${ENSDA}" = YES ]; then
-    export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
-  else
+################################################
+export FGAT_MODEL=${FGAT_MODEL:-gfs}
+export FGAT_HR=${FGAT_HR:-00}
+
+run_needed=NO
+if [ -d ${WORKhafs}/intercom/atm_merge_prep ]; then
+  echo 'outside parent domain'
+  run_needed=YES
+  export run_needed=YES
+fi
+
+if [[ "${run_needed}" = "YES" ]] && [[ ${MERGE_TYPE} = init ]] ; then
+
+  # Merge analysis or init
+  if [ ${MERGE_TYPE} = analysis ]; then
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
+    else
+      export DATA=${WORKhafs}/analysis_merge${jobidstr}
+    fi
+  elif [ ${MERGE_TYPE} = init ]; then
     if [ ${FGAT_MODEL} = gdas ]; then
       export DATA=${WORKhafs}/atm_merge_fgat${FGAT_HR}${jobidstr}
     else
       export DATA=${WORKhafs}/atm_merge${jobidstr}
     fi
+  else
+    echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
+    exit 1
   fi
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_merge_test.sh
+  export err=$?; err_chk
+
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 else
-  echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
-  exit 1
+
+  # Merge analysis or init
+  if [ ${MERGE_TYPE} = analysis ]; then
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
+    else
+      export DATA=${WORKhafs}/analysis_merge${jobidstr}
+    fi
+  elif [ ${MERGE_TYPE} = init ]; then
+    if [ "${ENSDA}" = YES ]; then
+      export DATA=${WORKhafs}/analysis_merge_ens/mem${ENSID}${jobidstr}
+    else
+      if [ ${FGAT_MODEL} = gdas ]; then
+        export DATA=${WORKhafs}/atm_merge_fgat${FGAT_HR}${jobidstr}
+      else
+        export DATA=${WORKhafs}/atm_merge${jobidstr}
+      fi
+    fi
+  else
+    echo "FATAL ERROR: unsupported MERGE_TYPE: ${MERGE_TYPE}"
+    exit 1
+  fi
+  
+  if [ "${ANALYSIS_MODEL}" = "JEDI" ] || [ "${ANALYSIS_MODEL}" = "jedi" ]; then
+   if [ ${ENSDA} = "YES" ] && [ ! -e "${COMOLD}" ] && [ ${MERGE_TYPE} = init ] ; then
+     echo "RUN_ENSDA YES for JEDI will skip ens merge for the first cycle"
+     echo "Do nothing. Exiting"
+     exit
+   fi
+  fi
+  
+  if [ "${SCRUBDATA:-YES}" = "YES" ]; then
+    rm -rf $DATA
+  fi
+  mkdir -p $DATA
+  cd $DATA
+  
+  # Execute ex-script
+  ${HOMEhafs}/scripts/exhafs_merge.sh
+  export err=$?; err_chk
+  
+  # Cleanup DATA dir
+  cd ${WORKhafs}
+  if [ "${KEEPDATA:-YES}" != "YES" ]; then
+    rm -rf $DATA
+  fi
+
 fi
-
-if [ "${ANALYSIS_MODEL}" = "JEDI" ] || [ "${ANALYSIS_MODEL}" = "jedi" ]; then
- if [ ${ENSDA} = "YES" ] && [ ! -e "${COMOLD}" ] && [ ${MERGE_TYPE} = init ] ; then
-   echo "RUN_ENSDA YES for JEDI will skip ens merge for the first cycle"
-   echo "Do nothing. Exiting"
-   exit
- fi
-fi
-
-if [ "${SCRUBDATA:-YES}" = "YES" ]; then
-  rm -rf $DATA
-fi
-mkdir -p $DATA
-cd $DATA
-
-# Execute ex-script
-${HOMEhafs}/scripts/exhafs_merge.sh
-export err=$?; err_chk
-
-# Cleanup DATA dir
-cd ${WORKhafs}
-if [ "${KEEPDATA:-YES}" != "YES" ]; then
-  rm -rf $DATA
-fi
-
 date
